version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8001"  # Le même port en interne et en externe
    volumes:
      - ./api/app:/app/app
      - ./Base_de_donnees:/app/Base_de_donnees
    environment:
      - DEBUG=True
      - PYTHONPATH=/app
      - HOST=0.0.0.0  
    env_file:
      - api/.env
    restart: unless-stopped
    networks:
      - api_network

networks:
  api_network:
    driver: bridge 